In [1]:
import pickle
import numpy as np

In [2]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [58]:
# Assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([2, 'male', 10.0, 0, 0, 'S'],dtype=object).reshape(1,6)

In [59]:
test_input

array([[2, 'male', 10.0, 0, 0, 'S']], dtype=object)

In [60]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

C:\Users\ujjwal raj\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [61]:
test_input_sex

array([[0., 1.]])

In [62]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [63]:
test_input_embarked

array([[0., 0., 1.]])

In [64]:
test_input_age = test_input[:,2].reshape(1,1)

In [65]:
test_input_age

array([[10.0]], dtype=object)

In [66]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [67]:
test_input_transformed.shape

(1, 9)

In [68]:
clf.predict(test_input_transformed)

array([1])