In [45]:
import numpy as np

In [46]:
np.random.random()

0.8946066635038473

In [47]:
np.random.seed(1)
np.random.random

<bound method RandomState.random of RandomState(MT19937) at 0x26BB896B940>

In [48]:
np.random.uniform(3,10)

5.9191540329180174

In [49]:
np.random.uniform(1,100,10).reshape(2,5)

array([[72.31212485,  1.01132311, 30.93092469, 15.52883319, 10.14152088],
       [19.43976093, 35.21051198, 40.27997995, 54.34285667, 42.50025693]])

In [56]:
np.random.randint(1,100,15).reshape(3,5)

array([[14, 10,  8, 64, 62],
       [23, 58,  2,  1, 61],
       [82,  9, 89, 14, 48]], dtype=int32)

In [57]:



#operations

In [59]:
a=np.random.randint(1,10,6)
a

array([4, 5, 9, 2, 5, 1], dtype=int32)

In [60]:
np.max(a)

np.int32(9)

In [61]:
np.min(a)

np.int32(1)

In [64]:
np.argmax(a)

np.int64(2)

In [65]:
np.argmin(a)

np.int64(5)

In [71]:
a=np.random.randint(1,10,6)
a

array([8, 9, 7, 4, 8, 8], dtype=int32)

In [74]:
a[a%2==1]=0
a

array([8, 0, 0, 4, 8, 8], dtype=int32)